### ISSUE TITLE
Linkedin-Bot: changes in the structure of the site.

### ISSUE THREAD

**Issue by EloyEMC** [FujiwaraChoki/linkedin-bot#2]
Hello, the Linkedin website structure has changed and the script does not work correctly.
This is the part you modified: ACTION_CONTAINER
Below I leave the changes applied in the corresponding section:

# ---- DON'T TOUCH ----
PEOPLE = []
MAX_PAGES = 10
BASE_LINKEDIN_URL = "https://www.linkedin.com"
RESULTS_LIST_CLASS = "reusable-search__entity-result-list"
PAGINATION_LIST_CLASS = "artdeco-pagination__pages"
PERSON_NAME_CLASS = "entity-result__title-text"
PERSON_SUBTITLE_CLASS = "entity-result__primary-subtitle"
PERSON_SECONDARY_SUBTITLE_CLASS = "entity-result__secondary-subtitle"
PERSON_SUMMARY_CLASS = "entity-result__summary"
PERSON_ACTION_BUTTON = "entity-result__actions"
ACTION_CONTAINER = "IZLqPHsLPvmtnxTRikvwkBUVdnExLjJlPwssjbtQ"
MODAL_ACTION_BAR = "artdeco-modal__actionbar"

**Comment by FujiwaraChoki** [comment]
THANK YOU
